# Generated by Django 4.0 on 2023-03-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('is_ustaz', models.BooleanField(default=False)),
                ('niche', models.CharField(choices=[('ADAB', 'ADAB'), ('HADITH', 'HADITH'), ('FALSAFA', 'FALSAFA')], default='ADAB', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
